// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RJeNIXY_acAJG19nTXo9ylMDz1iMUqw',
    appId: '1:538736334889:web:4e6930ef4e96a1c534a438',
    messagingSenderId: '538736334889',
    projectId: 'travel-app-fe009',
    authDomain: 'travel-app-fe009.firebaseapp.com',
    storageBucket: 'travel-app-fe009.appspot.com',
    measurementId: 'G-Y90TMF7WBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QzkvfIa9q_oE6OUoaZzrqXyTkiXW_Co',
    appId: '1:538736334889:android:ac430f9fca7f064134a438',
    messagingSenderId: '538736334889',
    projectId: 'travel-app-fe009',
    storageBucket: 'travel-app-fe009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIaatZckMIiRNWj7JrFw5wzjo3WgOasc',
    appId: '1:538736334889:ios:91aa70168a878e0a34a438',
    messagingSenderId: '538736334889',
    projectId: 'travel-app-fe009',
    storageBucket: 'travel-app-fe009.appspot.com',
    iosClientId: '538736334889-ucjd38804tthe3r8b9qbnmmnrsa9dlim.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelUi',
  );
}
