// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CW-FLVGZGHosuRuJBCQx4chw8tiJ0Z8',
    appId: '1:721732210668:web:2425fbc9e95bb2e6d27ac9',
    messagingSenderId: '721732210668',
    projectId: 'travel-app-cab09',
    authDomain: 'travel-app-cab09.firebaseapp.com',
    storageBucket: 'travel-app-cab09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfMbawESH2EQrGCQfY-e6rCtggUTFLp8',
    appId: '1:721732210668:android:6e5977ce021f0e66d27ac9',
    messagingSenderId: '721732210668',
    projectId: 'travel-app-cab09',
    storageBucket: 'travel-app-cab09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Q-USVBv1oo4T3ak340Aj6MVKNnhueRc',
    appId: '1:721732210668:ios:a2cfc1bc863ac624d27ac9',
    messagingSenderId: '721732210668',
    projectId: 'travel-app-cab09',
    storageBucket: 'travel-app-cab09.appspot.com',
    iosClientId: '721732210668-0ak3adi9t19a5j1aqtofv3qaqo4g7hpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelUi',
  );
}
